### ISSUE TITLE
Traefik and Loadbalancer Trouble

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/notification-api#523]
**Story**
When using the elastic load balancer traefik seems to emit random 500 errors and or the load balancer and we need to be able to track it down and stop them. 

**What?**
- Configure traefik to use the application load balancer instead of the elastic load balancer if possible, or remove traefik and just use application load balancer 

**Why?**
- When the loadbalancer passes back a 500 error to a client. 
- CSS paths returning 500 error on asset fingerprints.
- Get a better understanding of random 500 errors emitted by traefik
- Reduce overall number of technologies users by 1 simplifying support load

**Comment by timarney** [comment]
Possibly something to dig into 
https://github.com/containous/traefik/issues/3237#issuecomment-495749939

**Comment by maxneuvians** [comment]
One solution here was to replace the ELB loadbalancer with ALB. The solution is to change the Traefik service from `LoadBalancer` to `NodePort` and then specify the service ports with `NodePorts`. This is an example:

```
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
spec:
  ports:
    - protocol: TCP
      name: http
      nodePort: 30080
      port: 80
  selector:
    app: traefik
  type: NodePort
```

Where `http` is the name of an entrypoint in traefik. You can then set up an ALB in AWS with two security groups, one for internet ingress and one for communicating with the instances. You add a listener for the port ex 80 and have a target group on the nodeport `30080` that corresponds to that. Currently targets need to be managed manually. Once that is done you can use ALB in front of traefik.
